### ISSUE TITLE
Is it possible to have different colored lines for each indentation level? 

### ISSUE THREAD

**Issue by Santosh-Gupta** [spywhere/vscode-guides#48] opened 2020-03-04 20:15 UTC
As far as I've been able to checkout, I haven't seen an option for this. It would be a great clear, subtle way to comprehend the code geography of a particular line of code. There is rainbow indent, but it's too distracting during times when you aren't concerned about code geography.

**Comment by spywhere** [comment] 2020-03-13 10:01
That seems to be a duplicate of #16

**Closed as completed by spywhere** 2020-03-13 10:01 UTC
Labels: duplicate
