### ISSUE TITLE
Guides extension has detected that you are using "editor.renderIndentGuides" settings. Guides will now disable all indentation guides by override the style to "none".

### ISSUE THREAD

**Issue by ericyip** [spywhere/vscode-guides#18] opened 2017-06-09 03:38 UTC
After updating vscode today, I got this message. 
Guides is not working even I disable the editor.rederIndentGuides setting.

**Comment by ThinkRealize** [comment] 2017-06-09 06:28
I hava same problem when update vscode 1.13.0 (1.13.0)

**Comment by hungys** [comment] 2017-06-09 08:09
+1

**Comment by glaszczyk** [comment] 2017-06-09 08:24
The same and I can't activate Guides even with `"editor.renderIndentGuides": false`

**Comment by spywhere** [comment] 2017-06-09 08:52
Thanks for the issue. I'll take a look and let you know once I published.

**Comment by ViggoV** [comment] 2017-06-09 08:58
+1 - This is almost ruining my day :P

**Comment by spywhere** [comment] 2017-06-09 09:25
The fix has been published. The cause is due to the API changes in VSCode.

**Closed by spywhere** 2017-06-09 09:25 UTC
Labels: bug, investigate

**Comment by kevintechie** [comment] 2017-06-09 21:08
I still get this error with vscode 1.13.0 and guides 0.7.1.

**Comment by spywhere** [comment] 2017-06-10 02:21
@kevintechie Thanks for the update with the fix. I've done the quick fix there but still have to take a deep look onto the issue. Hopefully, I can update it properly by night (from my timezone though).

**Comment by spywhere** [comment] 2017-06-10 19:48
I've check the issue deeply and seems that the quick fix should help in this case. The cause of the problem is VSCode 1.12.2 use theme settings (`.dark`, `.light`) over base settings, however, VSCode 1.13.0 have this changed to let base settings have higher precedence over theme settings, which cause VSCode to render nothing if the base value is invalid (which in this case, it did). So in addition to this, Guides will now deprecate base configurations and will be removed in an upcoming version to totally remove the future possibility for this issue.

**Comment by kevintechie** [comment] 2017-06-12 16:47
@spywhere I have tried setting `guides.normal.color`, `guides.active.color` and `guides.stack.color` to some color (`rgba(255, 255, 255, 0.75)`), but I still get the error. Also, I now have Guides version 8.2 installed.

If i set editor.renderIndentGuides to false, vscode stops producing the warning.

**Comment by spywhere** [comment] 2017-06-12 17:08
@kevintechie Could you answer the following questions?

- How big is the file you are working with, in term of number of lines?
- What is your Guides configurations (every option count)?

And also, if possible...
- A screenshot from developer tools's console would be a great help
- Could you install [Extension API](https://marketplace.visualstudio.com/items?itemName=spywhere.extension-api), then run the command `Extension API: Evaluate...`, type in `vscode.workspace.getConfiguration("guides")` and send back the full output

**Comment by kevintechie** [comment] 2017-06-12 19:24
The file I'm working on is 54 lines.
I now have no guides settings at all.

Here is the output of Extension API:
```
Expression:vscode.workspace.getConfiguration("guides") 
Output:{  
   "active":{  
      "color":{  
         "dark":"rgba(120, 60, 60, 0.75)",
         "light":"rgba(200, 100, 100, 0.75)"
      },
      "enabled":true,
      "expandBrackets":true,
      "extraIndent":false,
      "gutter":false,
      "hideOnSelection":true,
      "style":"solid",
      "width":1
   },
   "indent":{  
      "backgrounds":[  

      ],
      "hideBackgroundOnSelection":true,
      "showFirstIndentGuides":true
   },
   "normal":{  
      "color":{  
         "dark":"rgba(60, 60, 60, 0.75)",
         "light":"rgba(220, 220, 220, 0.75)"
      },
      "enabled":true,
      "hideOnSelection":true,
      "style":"solid",
      "width":1
   },
   "overrideDefault":false,
   "sendUsagesAndStats":true,
   "stack":{  
      "color":{  
         "dark":"rgba(80, 80, 80, 0.75)",
         "light":"rgba(180, 180, 180, 0.75)"
      },
      "enabled":true,
      "hideOnSelection":true,
      "style":"solid",
      "width":1
   },
   "updateDelay":0.1
}
![guides](https://user-images.githubusercontent.com/10410717/27051179-0677cdf8-4f6a-11e7-8f76-b39e9d358afd.png)
```

**Comment by spywhere** [comment] 2017-06-13 15:06
@kevintechie I might need you to try out on a newer version where I remove base settings as all things are looking perfectly fine to me. Meanwhile, you might want to stick with the default indentation guides. I will let you know once I publish it and sorry for the inconvenience.

**Comment by thuyettiensinh** [comment] 2017-06-14 02:53
I hope you can fix this in last version !
Tks !

**Comment by AngeloAnolin** [comment] 2017-06-15 13:10
Having this issue as well with VS Code after updating today:
Version 1.13.1

And I can see the settings.json file has this line when I click on File | Preferences | Settings:
```
// Controls whether the editor should render indent guides
"editor.renderIndentGuides": true,
```

**Comment by egabrum** [comment] 2017-06-15 19:17
I have  Guides 0.8.2 and the error message was still showing up, even though `"editor.renderIndentGuides"` wasn't at all in my settings.json

The problem only went away when I added to my settings.json:
`"editor.renderIndentGuides": false,`

I think this issue should be re-opened.

**Comment by spywhere** [comment] 2017-06-16 00:59
@egabrum That's not an issue at all. Guides expected you to disable built-in indentation guides in order to work properly as it might overlap the indentation guides. But yeah, I'm considering to add a button next to the warning message to let you choose to stick with built-in indentation guides or from Guides one.

**Comment by spywhere** [comment] 2017-06-16 04:18
Guides v0.8.3 has been published. This should fix the case where people misunderstand `editor.renderIndentGuides` configuration, and also remove base value configurations.

**Comment by AngeloAnolin** [comment] 2017-06-16 12:55
@spywhere - I can confirm that the button now shows selecting between the built-in baked into VS Code and the Guides extension. Good stuff! =)

**Comment by Nick-Hope** [comment] 2017-11-18 14:24
Selecting the "Use Guides" button didn't work for me, so that warning bar came up every time I reopened vscode. I eventually had to put `"editor.renderIndentGuides": false` into the user settings to get it to go away and for Guides to work. VSCode 1.18.1. Guide 0.9.0.

**Comment by spywhere** [comment] 2017-11-18 14:25
@Nick-Hope Please file this on another issue. This issue was long close and doesn't relate to an issue with new version anymore.
