### ISSUE TITLE
Guides show warning when it auto disable itself

### ISSUE THREAD

**Issue by wenkeming** [spywhere/vscode-guides#19] opened 2017-06-12 09:39 UTC
![1](https://user-images.githubusercontent.com/8252267/27028125-67a6b356-4f96-11e7-8fc5-fe3b388a169d.png)
VS CODE version: 1.13.0
Guides extension has detected that you are using "editor.renderIndentGuides" settings. Guides will now disable all indentation guides by override the style to "none".

**Comment by spywhere** [comment] 2017-06-12 09:47
Please be more specific and also check [closed issues](https://github.com/spywhere/vscode-guides/issues?q=is%3Aissue+is%3Aclosed) for possibly duplicates. Issue like this not only take more time to gather the details but also harder to fix which result in longer update time.

If you just update your VSCode to 1.13.0, you may want to read [this first](https://github.com/spywhere/vscode-guides/issues/18). I'll close this issue eventually if there is no response.

**Comment by spywhere** [comment] 2017-06-12 09:49
Seems to be duplicate of #18. Will reopen again if the issue is not the same.

**Comment by spywhere** [comment] 2017-06-12 09:52
Reopened as this consists of 2 issues.

**Comment by spywhere** [comment] 2017-06-12 13:31
This issue has been fixed in v0.8.1

**Closed by spywhere** 2017-06-12 13:31 UTC
Labels: bug
