### ISSUE TITLE
Option arrays need defaulting.

### ISSUE THREAD

**Issue by ianwesterfield** [spywhere/vscode-guides#4] opened 2016-04-22 22:12 UTC
Both the `"guides.indent.backgrounds"` and `guides.rulers"` aren't being defaulted, so not adding them to the user settings results in exceptions as depicted below.

![guides error](https://cloud.githubusercontent.com/assets/15803541/14756154/31a631b0-08b5-11e6-9503-8d8c27302031.png)

**Comment by spywhere** [comment] 2016-04-23 03:31
Duplicate of #3

**Closed by spywhere** 2016-04-23 03:31 UTC
