### ISSUE TITLE
TypeError: Cannot read property 'document' of undefined 

### ISSUE THREAD

**Issue by aeschli** [spywhere/vscode-guides#2] opened 2016-04-06 08:44 UTC
From our error telemetry:

TypeError: Cannot read property 'document' of undefined 
 at Guides.updateEditor (/home/a123/.vscode-insiders/extensions/spywhere.guides-0.0.3/out/src/extension.js:71:41) 
 at GuidesController.updateEditor (/home/a123/.vscode-insiders/extensions/spywhere.guides-0.0.3/out/src/extension.js:23:21) 
 at e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/pluginHostProcess.js:7:14035) 
 at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/node/pluginHostProcess.js:7:15488) 
 at e._acceptActiveEditorAndVisibleEditors (/usr/share/code-insiders/resources/app/out/vs/workbench/node/pluginHostProcess.js:19:7974) 
 at e._acceptTextEditorRemove (/usr/share/code-insiders/resources/app/out/vs/workbench/node/pluginHostProcess.js:19:8379) 
 at t.e.handle (/usr/share/code-insiders/resources/app/out/vs/workbench/node/pluginHostProcess.js:15:12687) 
 at c (/usr/share/code-insiders/resources/app/out/vs/workbench/node/pluginHostProcess.js:11:16222) 
 at h (/usr/share/co

**Comment by spywhere** [comment] 2016-04-06 09:42
Thanks. I'll look through my extension if something could be helpful.

**Comment by jrieken** [comment] 2016-04-06 10:35
https://github.com/spywhere/vscode-guides/blob/master/src/extension.ts#L36 might be the cause since `activeTextEditor` is undefined from time to time

**Comment by spywhere** [comment] 2016-04-06 16:14
Thanks @jrieken. That could be it. I'll fix it once I'm on my computer as soon as possible.

**Comment by jrieken** [comment] 2016-04-06 17:35
Great. Also, there is an issue on our side that we are not consistent with a _falsy_ values, so sometimes it is `undefined` and sometimes `null`. Fix is on master, but until then it best to check for `!activeTextEditor`

**Comment by spywhere** [comment] 2016-04-07 04:40
The issue has been fixed in v0.0.4. I also add suggestion message for rulers since VSCode already supports it.

Side note: The icon path for `icon` in the `package.json` drive me crazy because there is a rule to ignore all images path in the `.vscodeignore` (which I added since I think that there is no use when install).

**Closed by spywhere** 2016-04-07 04:40 UTC
Labels: bug

**Comment by jrieken** [comment] 2016-04-07 08:11
> Side note: The icon path for icon in the package.json drive me crazy because there is a rule to ignore all images path in the .vscodeignore (which I added since I think that there is no use when install).

@joaomoreno fyi

**Comment by joaomoreno** [comment] 2016-04-07 08:14
I'm not sure I understand.

**Comment by spywhere** [comment] 2016-04-07 08:27
I have ignored the 'images' directory in the '.vscodeignore' file which leads to file not found due to the icon image is kept in that directory. This makes me confused because the error message saying that 'extension/images/icon.png' is not found but I have them in the proper location.

**Comment by joaomoreno** [comment] 2016-04-07 08:41
I assumed you're unblocked now, since I don't see that ignore rule anymore in the file. I'm happy you fixed it.

**Comment by spywhere** [comment] 2016-04-07 09:04
Yup, but that took a while. That's why I said I'm crazy with it.
